# Site settings
# in the templates available like {{ site.myvariable }}.
title: Woice
email: woice.ks@gmail.com
brand: Woice
headline: Inventor, Engineer and Futurist
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 2016 Whatever Company, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 259028

# Contacts
email: woice.ks@gmail.com
# phone: +1-800-555-2016

# Tracking
googleAnalitycsID: UA-83933844-1

